name: juneflow
description: "Description here"
publish_to: 'none'
#repository: https://github.com/melodysdreamj/juneflow

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  bot_toast: ^4.1.3
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_zoom_drawer: ^3.2.0
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  june: ^0.8.8
  keyboard_attachable: ^2.2.0
  modal_bottom_sheet: ^3.0.0
  styled_widget: ^0.4.1

dev_dependencies:
  bot_toast_module: ^0.1.2
  device_preview_module: ^1.0.0
  flutter_lints: ^3.0.2
  flutter_lints_module: ^1.0.1
  flutter_test:
    sdk: flutter
  hive_module: ^1.0.1
  june_view: ^1.5.10
  june_view_more: ^0.3.2
  screenutil_module: ^1.0.1

flutter:
  uses-material-design: true